// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Test.DAL.Models;

[Table("PostTag")]
public partial class PostTag
{
    [Key]
    public int PostTagId { get; set; }

    public int PostId { get; set; }

    public int TagId { get; set; }

    [Required]
    public byte[] Version { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostTags")]
    public virtual Post Post { get; set; }

    [ForeignKey("TagId")]
    [InverseProperty("PostTags")]
    public virtual Tag Tag { get; set; }
}