// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Test.DAL.Models;

[Table("Post")]
public partial class Post
{
    [Key]
    public int PostId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PostName { get; set; }

    [Required]
    public byte[] Version { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<PostTag> PostTags { get; set; } = new List<PostTag>();

    [InverseProperty("Posts")]
    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}