// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Test.DAL.Models;

[Table("Tag")]
public partial class Tag
{
    [Key]
    public int TagId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TagName { get; set; }

    [Required]
    public byte[] Version { get; set; }

    [InverseProperty("Tag")]
    public virtual ICollection<PostTag> PostTags { get; set; } = new List<PostTag>();

    [InverseProperty("Tags")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}